# This ansible playbook can be run locally using:
# ansible-playbook local.yml -K
# OR we can use this command to run it without making any changes.
# ansible-playbook local.yml -K --diff --check
# Most tasks need root privileges and for those we specify become_user: root.
# For others we need to be the non-root user and for that we have the variable
# non_root_user: brayan.

- name: Setting Up PC
  vars:
    non_root_user: brayan
  hosts: localhost
  connection: local
  become: true
  become_method: sudo
  become_user: '{{non_root_user}}'

  pre_tasks:
    - name: Update arch using pacman before any installations.
      import_tasks: ansible/tasks/pre_tasks.yml
      become: true
      become_user: root

  tasks:
    - name: Install command line tools using pacman/yay.
      import_tasks: ansible/tasks/pacman_install_cli_apps.yml
      become: true
      become_user: root

    - name: Install GUI apps using pacman/yay.
      import_tasks: ansible/tasks/pacman_install_gui_apps.yml
      become: true
      become_user: root

    - name: Install hyprland pre-requisits using pacman/yay.
      import_tasks: ansible/tasks/pacman_hyprland.yml
      become: true
      become_user: root

    - name: Install GUI apps using flatpak.
      import_tasks: ansible/tasks/flatpak_install_gui_apps.yml
      become: true
      become_user: '{{non_root_user}}'

    # - name: Download binary releases from repos not found on arch.
    #   import_tasks: ansible/tasks/bin_utils/download_bins.yml
    #   become: true
    #   become_user: '{{non_root_user}}'

    # - name: Symlink downloaded binaries to system bin folder so that it's in path.
    #   import_tasks: ansible/tasks/sym_bin_to_path/sym_bin_apps.yml
    #   become: true
    #   become_user: root

    # - name: Creat symlink from user gtk.css to root gtk.css.
    #   import_tasks: ansible/tasks/utils/user_root_gtk_symlink.yml
    #   become: true
    #   become_user: root

    - name: Start ssh-agent service.
      import_tasks: ansible/tasks/systemd/ssh.yml
      become: true
      become_user: '{{non_root_user}}'
