# This ansible playbook can be run locally using:
# ansible-playbook local.yml -K

- name: Setting Up PC
  vars:
    non_root_user: brayan
  hosts: localhost
  connection: local
  become: true
  become_method: sudo
  become_user: '{{non_root_user}}'

  pre_tasks:
    - name: Update arch using pacman before any installations.
      import_tasks: ansible/tasks/pacman_update_arch.yml
      become: true
      become_user: root

  tasks:
    - name: Install command line tools using pacman/yay.
      import_tasks: ansible/tasks/pacman_install_cli_apps.yml
      become: true
      become_user: root

    - name: Install GUI apps using pacman/yay.
      import_tasks: ansible/tasks/pacman_install_gui_apps.yml
      become: true
      become_user: root

    - name: Install GUI apps using flatpak.
      import_tasks: ansible/tasks/flatpak_install_gui_apps.yml
      become: true
      become_user: '{{non_root_user}}'
