- name: Upgrade all flatpaks.
  ansible.builtin.command: flatpak update --noninteractive
  register: flatpak_update_output
  changed_when: "'app/' in flatpak_update_output.stdout"

- name: Remove the flathub remote from the user installation.
  community.general.flatpak_remote:
    name: flathub
    state: absent
    method: user

- name: Add the flathub repository remote to the system installation.
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: system

- name: Install gui apps from flathub for entire system.
  community.general.flatpak:
    name:
      # Manage EVERYTHING flatpak apps realated settings.
      - io.github.flattool.Warehouse
      # Manage app premissions.
      - com.github.tchx84.Flatseal
      - us.zoom.Zoom
      - com.brave.Browser
      # Best image viewer.
      - org.nomacs.ImageLounge
      - io.gitlab.librewolf-community
      - com.dec05eba.gpu_screen_recorder
      - org.gimp.GIMP
      # Resynthesizer, a healing tool for gimp. All the following packages
      # are needed as a dependency.
      - org.gimp.GIMP.Plugin.Resynthesizer
      - org.gimp.GIMP.Plugin.LiquidRescale
      - org.gimp.GIMP.Plugin.Lensfun
      - org.gimp.GIMP.Plugin.GMic
      - org.gimp.GIMP.Plugin.Fourier
      - org.gimp.GIMP.Plugin.FocusBlur
      - org.gimp.GIMP.Plugin.BIMP
      # Manage gtk/adwaita colors/themes.
      # After installing run this commands:
      # Sets gtk3 theme.
      # gsettings set org.gnome.desktop.interface gtk-theme 'adw-gtk3-dark'
      # Sets apps to prefer dark mode version of themes.
      # gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
      - org.gtk.Gtk3theme.adw-gtk3
      - org.gtk.Gtk3theme.adw-gtk3-dark
      # Needed to change qt applications theme installed via flatpak.
      # You need to install all org.kde.KStyle.Kvantum with the same version of org.kde.Platform
      # Check org.kde.Platform version using: flatpak list | rg org.kde.Platform
      # Then run: sudo flatpak override --env=QT_STYLE_OVERRIDE=kvantum --filesystem=xdg-config/Kvantum:ro
      - org.kde.KStyle.Kvantum
      # Send files/text over local network.
      - org.localsend.localsend_app
      # Streaming client for moonshine.
      - com.moonlight_stream.Moonlight
    state: present
    method: system

- name: Install gnome gui apps from flathub for entire system user if DE is gnome.
  community.general.flatpak:
    name:
      # App to manage Gnome extensions.
      - com.mattjakeman.ExtensionManager
    state: present
    method: system
  when: current_DE is search("gnome")
