- name: Make timeshift backup IFF on a btrfs drive.
  shell: "timeshift --create --comments 'Made before Ansible made changes.'"
  when: ansible_mounts is search("btrfs")

# Start making changes to system.
- name: Full system upgrade for Arch Linux using Pacman.
  community.general.pacman:
    update_cache: true
    upgrade: true
    # Do not installed already installed packages and assume yes to prompts.
    extra_args: --needed --noconfirm --ask=4
