vars:
  tcp_ports:
  - 53317 # localsend
  - 22000 # syncthing
  - 22067 # syncthing relay
  - 22070 # syncthing relay

  udp_ports:
  - 53317 # localsend
  - 546 # dhcpv6-client
  - 22000 # syncthing
  - 21027 # syncthing

tasks:
  - name: Opening needed tcp ports.
    ansible.posix.firewalld:
        zone: public
        port: "{{ item }}/tcp"
        permanent: true
        state: enabled
        immediate: true
    loop: "{{ tcp_ports }}"

  - name: Opening needed udp ports.
    ansible.posix.firewalld:
        zone: public
        port: "{{ item }}/udp"
        permanent: true
        state: enabled
        immediate: true
    loop: "{{ tcp_ports }}"
