- name: Create symlinks in child directories
  find:
    paths: "~/.zen"
    file_type: directory
    depth: 1
  register: child_dirs

- name: Create symlinks
  file:
    src: "~/.zen/zen-keyboard-shortcuts.json"
    dest: "{{ item.path }}/zen-keyboard-shortcuts.json"
    state: link
  loop: "{{ child_dirs.files }}"
  when: item.path != "~/.zen"
