- name: Remove the flathub remote from the system installation.
  community.general.flatpak_remote:
    name: flathub
    state: absent
    method: user

- name: Add the flathub repository remote to the user installation.
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: system

- name: Install gui apps from flathub for current user.
  community.general.flatpak:
    name:
      - com.github.tchx84.Flatseal
      - us.zoom.Zoom
      - com.brave.Browser
      - org.nomacs.ImageLounge
      - io.gitlab.librewolf-community
      - com.dec05eba.gpu_screen_recorder
    state: present
    method: system

- name: Install gnome gui apps from flathub for current user if DE is gnome.
  community.general.flatpak:
    name:
      # App to manage Gnome extensions.
      - com.mattjakeman.ExtensionManager
    state: present
    method: system
  when: current_DE is search("gnome")
