- name: Remove the flathub remote from the user installation.
  community.general.flatpak_remote:
    name: flathub
    state: absent
    method: user

- name: Add the flathub repository remote to the system installation.
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: system

- name: Install gui apps from flathub for entire system.
  community.general.flatpak:
    name:
      # Manage app premissions.
      - com.github.tchx84.Flatseal
      - us.zoom.Zoom
      - com.brave.Browser
      # Best image viewer.
      - org.nomacs.ImageLounge
      - io.gitlab.librewolf-community
      - com.dec05eba.gpu_screen_recorder
      - org.gimp.GIMP
      # Resynthesizer, a healing tool for gimp. All the following packages
      # are needed as a dependency.
      - org.gimp.GIMP.Plugin.Resynthesizer
      - org.gimp.GIMP.Plugin.LiquidRescale
      - org.gimp.GIMP.Plugin.Lensfun
      - org.gimp.GIMP.Plugin.GMic
      - org.gimp.GIMP.Plugin.Fourier
      - org.gimp.GIMP.Plugin.FocusBlur
      - org.gimp.GIMP.Plugin.BIMP
    state: present
    method: system

- name: Install gnome gui apps from flathub for entire system user if DE is gnome.
  community.general.flatpak:
    name:
      # App to manage Gnome extensions.
      - com.mattjakeman.ExtensionManager
    state: present
    method: system
  when: current_DE is search("gnome")
