- name: From repos AND AUR, install GUI apps and their dependencies using pacman.
  community.general.pacman:
    name:
      - visual-studio-code-bin
      # - chromium
      # MS Office alternative and spell check tools.
      - libreoffice-fresh
      - hunspell
      - hunspell-en_us
      - hunspell-es_any
      - hunspell-es_gt
      - hunspell-es_mx
      # Re-arrange pdf pages or remove them or combine multiple pdfs.
      - pdfarranger
      # GPU accelerated terminal emulator.
      - alacritty
      # Disk management, partition resizer, etc.
      - gparted
      # Needed by gparted to check for errors.
      - gpart
      # Simple media player.
      - mpv
      # Media player.
      - vlc
      # Image viewer. Flatpak preferred.
      # - nomacs
      # Auto detect text on PDFs/images and tools needed.
      - gimagereader-qt
      - tesseract-data-eng
      - tesseract-data-spa
      # Change mkv video metadata.
      - mkvtoolnix-gui
      # Identify and add metadata to songs.
      - picard
      # Music player.
      - strawberry
      # Torrent client.
      - qbittorrent
      # Easily add/configure printers.
      - system-config-printer
      - mediaelch
      # Install flatpaks on the system.
      - flatpak
      # Sync files between computers.
      - syncthing
      # Pixel art map/level editor. Alternative to Tiled.
      - ldtk
      # Retroarch and needed packages. Must change config to download cores/assets from within retroarch.
      - retroarch
      # Playstation like theme.
      - retroarch-assets-xmb
      # List of cores available for download from within retroarch.
      - libretro-core-info
    state: present
    # Do not installed already installed packages and assume yes to prompts.
    extra_args: --needed --noconfirm --ask=4

- name: From repos AND AUR, install GNOME GUI apps and their dependencies using pacman.
  community.general.pacman:
    name:
      # Tool to change some things on gnome. Font size especially.
      - gnome-tweaks
    state: present
    # Do not installed already installed packages and assume yes to prompts.
    extra_args: --needed --noconfirm --ask=4
    when: current_DE is search("gnome")

- name: From repos AND AUR, install KDE/PLASMA GUI apps and their dependencies using pacman.
  community.general.pacman:
    name:
      - xdg-desktop-portal
      - xdg-desktop-portal-kde
      - qt5-imageformats
      - kdegraphics-thumbnailers
      # Needed to use nightlight plugin on kde desktop.
      - kdeplasma-addons
      - ffmpegthumbs
    state: present
    # Do not installed already installed packages and assume yes to prompts.
    extra_args: --needed --noconfirm --ask=4
    when: current_DE is search("plasma")

# TODO: Get file system name.
- name: From repos AND AUR, install timeshift and dependencies using pacman if using btrfs file system.
  community.general.pacman:
    name:
      # Show btrfs snapshots in the grub startup menu.
      - grub-btrfs
      # Take system snapshots. Works specially great with btrfs file system.
      - timeshift
      # Takes snapshop of system before updates automatically using timeshift.
      - timeshift-autosnap
    state: present
    # Do not installed already installed packages and assume yes to prompts.
    extra_args: --needed --noconfirm --ask=4
    when: current_DE is search("plasma")

- name: Remove conflicting packages.
  community.general.pacman:
    name:
      - libreoffice-still
    state: absent

- name: Remove conflicting plasma/kde packages.
  community.general.pacman:
    name:
      - ffmpegthumbnailer
    state: absent
    when: current_DE is search("plasma")