- name: From repos AND AUR, install hyprland specific nececities.
  community.general.pacman:
    name:
      # Some icons are not present in nerd fonts so I still need this for now.
      - otf-font-awesome
      # Hyprland itself.
      - hyprland
      # lock utility for hyprland.
      - hyprlock
      # Utility to set a wallpaper.
      - hyprpaper
      # idle utility for hyprland.
      - hypridle
      # Small qt/qml application to see system info.
      # - hyprsysteminfo
      # To make sure screensharing works.
      - pipewire
      - wireplumber
      # Needed for the hypridle config.
      - brightnessctl 
      # A clipboard for wayland. Mainly needed for clipse to be able to copy
      # binary data like images.
      - wl-clipboard
      # Needed for screenshoot script.
      - grim
      - slurp
      - hyprpicker
      # Needed to send notifications. Provides notify-send command.
      - libnotify
      # GTK3 settings editor that works on wlroots environment.
      # Not necessarily for hyprland only but wayland with wlroots is required.
      # When installed it also goes by gtk settings.
      - nwg-look
      # This package used to be in the AUR but is now in main repos.
      # - adw-gtk3
      # Needed to change qt apps theme.
      - qt5ct
      - qt6ct
      - qt5-wayland
      - qt6-wayland
      # Needed for qt5 apps.
      - kvantum-qt5
      # Theme qt6 and qt5 (kvantum-qt5 needed) apps.
      - kvantum
      # I like to use Catppuccin-Mocha-Yellow for QT and Ayu Dark for GTK.
      - kvantum-theme-catppuccin-git
      # Allow for screen recording.
      - xdg-desktop-portal-hyprland
      - xdg-desktop-portal-gtk
      # Share wayland windows from x11 applications. For example, sharing
      # firefox window running on wayland on zoom which is an x11 app.
      - xwaylandvideobridge
      # App launcher.
      - fuzzel
      # A status bar for wayland compositors.
      - waybar
      # Notification deamon.
      - swaync
      # Start authentication agent for apps that need a pop up to ask for pass.
      # - polkit-kde-agent
      # The kde polkit was crashing when using kvantum so this is working better.
      # On wayland, when an application closes, if anything was copied, it is
      # lost. This keeps it in memory. A clipboard history manager like
      # clipse still needs something like this.
      # ERROR: This makes wezterm crash right now on text selection.
      - wl-clip-persist
      # A polkit agent just asks for sudo priviliges for when GUI applications need root acces such as the Timeshift GUI application.
      # This is the polkit agent from the mate desktop which is a gtk3 or 2 (?) application.
      - mate-polkit
      # The polkit agent from hyprland.
      # - hyprpolkitagent
      # # Provides gnome-keyring-daemon to manage secrets, passwords, ssh and pgp keys.
      - gnome-keyring
      # Needed by gnome-keyring to manage secrets of gui apps.
      - libsecret
      # Gui application to manage gnome-keyring contents.
      - seahorse
      # Various criptographic tools, mainly, gcr-ssh-agent to keep ssh keys in cache.
      # gcr-ssh-agent, a wrapper around ssh-agent is needed by gnome-keyring-daemon to manage ssh keys.
      - gcr-4
      # WARNING: libsecret is prefered for gnome-keyring, but libgnome-keyring sometimes is still needed by some applications. Install it if an application is not having it's passwords saved.
      # - libgnome-keyring
      ##########################################################################
      # iwd can also be used as a wifi backend for NetworkManager, instead of wpa-supplicant. Although iwd is much newer, it is recommended as a better, nicer wifi backend. This is separate from using iwd as your wifi solution. In this case, NetworkManager will be your general networking solution, but you will be using iwd as the method to handle specifically wifi in the background, and you will use NetworkManager's commandline or GUI tools to connect, rather than iwctl or iwd-related tools.
      ##########################################################################
      # Applet to connect to wifi/ethernet for NetworkManager.
      - network-manager-applet
      - iwd
      # Gui front-end to iwd. Manage wifi network connections only.
      # - iwgtk
      # pipewire gui for volume control of input/output devices and streams.
      - pavucontrol
      #
      # OTHER APPS that ONLY work on hyprland/wl-roots compositors.
      #
      # Record wiht hardware encoding support.
      - wl-screenrec
      # Eaach vendor, nvidia, intel, etc, provide a way to use video harware
      # acceleration. But a lot of software doesn't use that specific way.
      # Instead they use the more generic form that works on all devices, vaapi.
      # So, we need the driver for the device to use it's native video hardware
      # acceleration, such as nvidia/intel drivers. Nvidia offers NVDEC as way
      # to decode/encode video in NEWER nvidia cards.
      # But we need a layer to translate between the vaapi calls that mpv or 
      # wl-screenrec make to NVDEC.
      # For NEWER nvidia cards this is libva-nvidia-driver, then we have access
      # to vappi running on newer nvidia cards.
      # Intel is easier since the driver is pre-installed on most linux distros,
      # but we still need to the vaapi implementation.
      # The intel-media-driver works with newer intel cpus and thats all we need
      # to have acces to vaapi.
      # WARNING: only use one implementation of vaapi, I am not completely sure,
      # but I think they overlap in some way. I want to try to use an env
      # variable to see if I can tell it which implementation to use.
      # Provides vainfo to check for vaapi support.
      - libva-utils
      # Needed for vaapi to work on newer intel igpus.
      # - intel-media-driver
      # Needed for vaapi to work on newer nvidia gpus.
      # - libva-nvidia-driver
      # The vulkan version of libva-utils used for vaapi. 
      # Provided vulkaninfo to check for vulkan support.
      - vulkan-tools
      # Tool to download list of mirrors from github, rate them, and write them out.
      # Update mirror list for endeavouros and save.
      # sudo rate-mirrors --allow-root --save /etc/pacman.d/endeavouros-mirrorlist endeavouros
      # Update mirror list for archlinux and save.
      # sudo rate-mirrors --allow-root --save /etc/pacman.d/mirrorlist arch
      - rate-mirrors
    state: present
    # Do not installed already installed packages and assume yes to prompts.
    extra_args: --needed --noconfirm --ask=4


# - name: Install packages from AUR using a Pacman compatible AUR helper
#   community.general.pacman:
#     name: foo
#     state: present
#     executable: yay
#     extra_args: --builddir /var/cache/ya
