- name: From repos AND AUR, install command line tools using pacman.
  community.general.pacman:
    name:
      # Make sure yay, the AUR helper is installed.
      - yay
      # Paru is the same as yay but it can be faster for searches for example.
      - paru
      - git
      # Fuzzel and Joplin. Patched with nerd fonts.
      - ttf-firacode-nerd
      # Terminal and VS Code font. Patched with nerd fonts.
      - ttf-jetbrains-mono-nerd
      # UI, like swaync, text font. Patched with nerd fonts.
      - ttf-roboto-mono-nerd
      # Open source google emoji font
      - noto-fonts-emoji
      # For a cli terminal we only need libqalculate and run qalc
      - libqalculate
      # Needed by qalc to display plots using the plot() function.
      - gnuplot
      # To use this same library but with GUI frontend we need the following.
      # - qalculate-qt
      # Better interactive shell but non-posix compliant.
      - fish
      # Terminal powerline.
      - starship
      # System monitor. Use btm on terminal.
      - bottom
      # Can monitor many types of gpus and integrated gpus.
      - nvtop
      # Better manpages and tldr. Knows about fewer apps than manpages.
      - tealdeer
      # Better shell history search.
      - atuin
      # Colors output with rainbow colors.
      - lolcat
      # neofetch alternative written in c.
      - fastfetch
      # neofetch but instead of system details, it gives git details.
      - onefetch
      # Tool to manipulate images. Good for resizing.
      - imagemagick
      # Raw image converter.
      - dcraw
      # All in one video/audio/image manipulation.
      - ffmpeg
      # Show metadata of media files.
      - mediainfo
      # Provides cli tool exiftool. Used to read image metadata.
      - perl-image-exiftool
      # Similar to exiftool but newer.
      - exiv2
      # Rename and tag music files.
      # - beets
      # Requirements for beets to fingerprint files.
      # - python-pyacoustid # Requirements for beets to fingerprint files.
      # - chromaprint
      # Requirements for beets to make API calls to MusicBrainz.
      # - python-requests
      # Alternative to cat. Shows contents of text files.
      - bat
      # Not sure how to use this yet. But it's nice that it has many formats as
      # output.
      - chroma-bin
      # System monitor. bottom can be used to look like htop but nicer.
      # - htop
      # Alternative to grep.
      - ripgrep
      # Interactive version of ripgrep. Use ig to run.
      - igrep
      # Alternative to find.
      - fd
      # Syncing utility.
      - rsync
      # Alternative to ls, shows files and directories with icons. Needs nerd font.
      - lsd
      # Very very very similar to lsd. Not sure what the diferences are.
      - eza
      # A all in one ls, glow, and more. Use g to launch command. Faster than
      # lsd but doesn't have as many icons.
      - g-ls
      # Easier sed command for find and replace.
      - sd
      # TUI alternative for git written in go.
      - lazygit
      # Better diff/pager.
      - git-delta
      # Another diff alternative but that understands syntax. Run with difft
      - difftastic
      # AUR: tui to manage docker containers.
      # - lazydocker
      # Friendly TUI alternative for git written in Rust. Not as nice as lazygit.
      - gitui
      # Alternative to cd but much better. It remembers folders visited.
      - zoxide
      # Dotfiles manager.
      - chezmoi
      # Provides shell components to quickly build god looking scripts.
      - gum
      # Record gifs/videos of terminal commands by recording a session or writing script.
      - vhs
      # To make pretty pictures of source code.
      - silicon
      # NOT IN REPOS OR AUR. AUR version is just source code.
      # Take images of source code or terminal command output.
      # https://github.com/charmbracelet/freeze/releases
      # Terminal file manager. move, create, rename, preview files/directories.
      - yazi
      # Search anything. By default, search files using find.
      - fzf
      # View images on terminals. MANY output formats and options. Mainly used to preview images in terminal.
      - chafa
      - ansible
      # Ansible dependency for json_query. Can also be installed with pip.
      - python-jmespath
      # Disk usage analyzer. Launch with dua interactive. Run with "dua i".
      - dua-cli
      # Disk usage analyzer. Barely better in some ways than dua.
      - ncdu
      # Disk usage tui.
      - duf
      # benchmark commands.
      - hyperfine
      # Markdown preview from the terminal.
      - glow
      # Alternative to T-mux. A terminal multiplexer.
      #- zellij
      # Alternative to neovim/vim/nano.
      - helix
      # Automagically source .envrc files on cd.
      - direnv
      # Run arbitrary command on file change.
      - entr
      - neovim-nightly-bin
      # - mkvtoolnix-cli
      # Recover deleted files and partitions. Just run and follow directions.
      - testdisk
      # Parse json in the terminal.
      - jq
      # Command-line YAML, XML, TOML processor - jq wrapper for YAML/XML/TOML documents
      - yq
      # Live preview of your command. Example: lshw |& up
      # In the example lshw pipes text into up and now we can use grep or any
      # other tool to interact with that text.
      - up
      # Terminal music player with vim-like keybindings.
      - cmus
      # Change the volume of mp3 files without losing quality.
      - mp3gain
      # Check for typos on text files. typos --diff --color always
      - typos
      # Conda alternative but uses pypi repos. Maybe better for python.
      - rye
      # Conda alternative but can use pypi repos AND conda repos.
      # It can also manage other runtimes, not just python.
      - pixi
      # JAVA DEVELOPMENT.
      # Java/kotlin build system.
      # - gradle
      # - jre17-openjdk
      # - jdk17-openjdk
      # - jre17-openjdk-headless
      # AUR LSP for java. Used by Helix.
      # - jdtls
      # C-SHARPT DEVELOPMENT.
      # - dotnet-sdk-6.0
      # - dotnet-runtime-6.0
      # AUR C-sharp LSP. Needed for Helix.
      # - omnisharp-roslyn
      # Language sever for yaml documents. Needed for Helix.
      - yaml-language-server
      # Tex file editing dependency packages.
      # - texlive
      # dvisvgm can convert tex files source files and pdfs to svg.
      # - texlive-dvisvgm
      # LSP/CLI tool for toml files.
      - taplo-cli
      # Language server for bash.
      - bash-language-server
      # Language server for json/jsonc.
      - vscode-json-languageserver
      # Language server for makdown. Does not format, need dprint.
      - marksman
      # Tool to upload files to immich server.
      - immich-go
    state: present
    # Do not installed already installed packages and assume yes to prompts.
    extra_args: --needed --noconfirm --ask=4

- name: Remove conflicting packages.
  community.general.pacman:
    name:
      - neovim
    state: absent
