- name: From repos AND AUR, install command line tools using pacman.
  community.general.pacman:
    name:
      # Make sure yay, the AUR helper is installed.
      - yay
      - git
      # Terminal font. Patched with nerd fonts.
      - ttf-firacode-nerd
      # VS Code font. Patched with nerd fonts.
      - ttf-jetbrains-mono-nerd
      # Open source google emoji font
      - noto-fonts-emoji
      # Replaces bash.
      #- zsh
      # Better interactive shell but non-posix compliant.
      - fish
      # Terminal powerline.
      - starship
      # System monitor. Use btm on terminal.
      - bottom
      # Better shell history search.
      - atuin
      # Colors output with rainbow colors.
      - lolcat
      # To show off system and setup.
      - neofetch
      # To make pretty pictures of source code.
      - silicon
      # Tool to manipulate images. Good for resizing.
      - imagemagick
      # Raw image converter.
      - dcraw
      # All in one video/audio/image manipulation.
      - ffmpeg
      # Show metadata of media files.
      - mediainfo
      # Rename and tag music files.
      # - beets
      # Requirements for beets to fingerprint files.
      # - python-pyacoustid
      # Requirements for beets to fingerprint files.
      # - chromaprint
      # Requirements for beets to make API calls to MusicBrainz.
      # - python-requests
      # Alternative to cat. Shows contents of text files.
      - bat
      # System monitor.
      - htop
      # Alternative to grep.
      - ripgrep
      # Alternative to find.
      - fd
      # Alternative to ls, shows files and directories with icons. Needs nerd font.
      - lsd
      # TUI alternative for git written in go.
      - lazygit
      # Friendly TUI alternative for git written in Rust. Not as nice as lazygit.
      - gitui
      # Alternative to cd but much better. It remembers folders visited.
      - zoxide
      # Terminal file manager. move, create, rename, preview files/directories.
      - yazi
      # Search anything. By default, search files.
      - fzf
      - ansible
      # Disk usage analyzer. Launch with dua interactive. Run with "dua i".
      - dua-cli
      # Disk usage analyzer. Barely better in some ways than dua.
      - ncdu
      # Markdown preview from the terminal.
      - glow
      # Alternative to T-mux. A terminal multiplexer.
      #- zellij
      # Alternative to neovim/vim/nano.
      - helix
      # - neovim-nightly-bin
      # - mkvtoolnix-cli
      # Recover deleted files and partitions. Just run and follow directions.
      - testdisk
      # JAVA DEVELOPMENT.
      # Java/kotlin build system.
      - gradle
      - jre17-openjdk
      - jdk17-openjdk
      - jre17-openjdk-headless
      # AUR LSP for java. Used by Helix.
      - jdtls
      # C-SHARPT DEVELOPMENT.
      - dotnet-sdk-6.0
      - dotnet-runtime-6.0
      # AUR C-sharp LSP. Needed for Helix.
      - omnisharp-roslyn
      # Language sever for yaml documents. Needed for Helix.
      - yaml-language-server
      # Tex file editing dependency packages.
      - texlive
      # dvisvgm can convert tex files source files and pdfs to svg.
      - texlive-dvisvgm
    state: present
    # Do not installed already installed packages and assume yes to prompts.
    extra_args: --needed --noconfirm --ask=4

- name: Remove conflicting packages.
  community.general.pacman:
    name:
      - neovim
    state: absent
