- name: From repos AND AUR, install GUI apps and their dependencies using pacman.
  community.general.pacman:
    name:
      # Needed to change qt apps theme.
      - qt5ct
      - qt6ct
      - qt5-wayland
      - qt6-wayland
      - kvantum
      # - firefox
      # AUR: a browser based on firefox but nicer to use with more features.
      - zen-browser-bin
      # MS Office alternative and spell check tools.
      - libreoffice-fresh
      - hunspell
      - hunspell-en_us
      - hunspell-es_any
      - hunspell-es_gt
      - hunspell-es_mx
      # Re-arrange pdf pages or remove them or combine multiple pdfs.
      - pdfarranger
      # Easy way to look at fonts installed, their full names, and more.
      - font-manager
      # GPU accelerated terminal emulator. I still use it to launch tui apps
      # like clipse fast. Wezterm is slightly slower but noticible.
      - alacritty
      #- kitty
      - wezterm
      # Disk management, partition resizer, etc.
      - gparted
      # Needed by gparted to check for errors.
      - gpart
      # Simple media player.
      - mpv
      # Add thumbnail preview to mpv timeline while moving mouse over it.
      # https://github.com/po5/thumbfast
      # Better mpv gui. Make sure to remove binaries that add the ability to
      # download subtitles from the internet.
      # https://github.com/tomasklaen/uosc
      # Media player.
      - vlc
      # Image viewer. Flatpak preferred.
      # - nomacs
      # Auto detect text on PDFs/images and tools needed.
      - gimagereader-qt
      - tesseract-data-eng
      - tesseract-data-spa
      # Change mkv video metadata.
      # - mkvtoolnix-gui
      # Identify and add metadata to songs.
      - picard
      # Music player. A cli music player is better. cmus for example.
      # - strawberry
      # Uses ffmpeg in the backend to transcode videos.
      # - handbrake
      # Torrent client.
      - qbittorrent
      # Easily add/configure printers.
      - system-config-printer
      # Install flatpaks on the system.
      - flatpak
      # Sync files between computers. Not necessarily a gui ap.
      # systemctl --user enable syncthing.service
      # systemctl --user start syncthing.service
      - syncthing
      # Disk benchmarking utility.
      - kdiskmark
      # Pixel art map/level editor. Alternative to Tiled.
      # - ldtk
      # Retroarch and needed packages. Must change config to download cores/assets from within retroarch.
      - retroarch
      # Playstation like theme.
      - retroarch-assets-xmb
      # List of cores available for download from within retroarch.
      - libretro-core-info
      # Lightroom alternative. Needs opencl for hardware
      # acceleration.
      # For nvidia cards we need opencl-nvidia
      # For intel integrated graphics we need intel-compute-runtime
      # Run darktable-cltest to check if it's working.
      # Don't forget to disable xml creation.
      - darktable
      # Photoshop alternative. Some plugins are easier to install with the
      # flatpak version so that is prefered.
      # - gimp
      # Easier to use stable diffusion with it.
      # - krita
      # Content aware healing from AUR.
      # - gimp-plugin-resynthesizer-git
      # Audio editor/recorder.
      - audacity
      # Downloads manager written in java.
      #- jdownloader2
      # - sunshine
      # Run ai models easily from the command line.
      # - ollama
      # # Install this for nvidia cards.
      # - ollama-cuda
      # Manage and run text2image models.
      # - invokeai
      # Uses ollama as backedn to anwer and run tasks on the terminal.
      # Has a minimal server that we can use a browser to navigate to it and have
      # a ui for the ai.
      # WARNING: This doesnt seem to be as useful as aider.chat
      # - aichat
      # Zed and lapce are both performance driven editors with great vim
      # motion support.
      - zed
      # - lapce
      # THE open source game engine.
      - godot
      # Markdown note taking.
      - zettlr
      # A daw like fl studio, lmms, etc.
      - reaper
    state: present

- name: From repos AND AUR, install GNOME GUI apps and their dependencies using pacman.
  community.general.pacman:
    name:
      # Tool to change some things on gnome. Font size especially.
      - gnome-tweaks
    state: present
  when: current_DE is search("gnome")

- name: From repos AND AUR, install KDE/PLASMA GUI apps and their dependencies using pacman.
  community.general.pacman:
    name:
      # Desktop integration portals for sandboxed apps such as flatpaks, appimages and gtk apps on kde DE.
      - xdg-desktop-portal
      - xdg-desktop-portal-kde
      # Plugins for additional image formats: TIFF, MNG, TGA, WBMP
      - qt5-imageformats
      # Allow KDE pps to show thumbnails for PostScript, RAW, Mobipocket, and Blender files.
      - kdegraphics-thumbnailers
      # Needed to use nightlight plugin on kde desktop.
      - kdeplasma-addons
      # FFmpeg-based thumbnail creator for video files.
      - ffmpegthumbs
    state: present
  when: current_DE is search("kde")

- name: From repos AND AUR, install timeshift and dependencies using pacman if using btrfs file system.
  community.general.pacman:
    name:
      # Show btrfs snapshots in the grub startup menu.
      - grub-btrfs
      # Take system snapshots. Works specially great with btrfs file system.
      - timeshift
      # Takes snapshop of system before updates automatically using timeshift.
      - timeshift-autosnap
    state: present
  when: ansible_mounts is search("btrfs")

- name: Remove conflicting packages.
  community.general.pacman:
    name:
      - libreoffice-still
    state: absent

- name: Remove conflicting plasma/kde packages.
  community.general.pacman:
    name:
      - ffmpegthumbnailer
    state: absent
  when: current_DE is search("kde")
