- name: From repos AND AUR, install command line tools using pacman.
  community.general.pacman:
    name:
      - ttf-firacode-nerd
      - ttf-jetbrains-mono-nerd
      - zsh
      - starship
      - bottom
      - lolcat
      - neofetch
      - silicon
      - mediainfo
      - beets
      - python-pyacoustid
      - chromaprint
      - python-requests
      - bat
      - htop
      - ripgrep
      - fd
      - lsd
      - lazygit
      - zoxide
      - fzf
      - ansible
      - zellij
      - helix
      - neovim-nightly-bin
      - mkvtoolnix-cli
      - testdisk
    state: present

- name: Remove conflicting packages.
  community.general.pacman:
    name:
      - neovim
    state: absent
