- name: From repos AND AUR, install hyprland specific nececities.
  community.general.pacman:
    name:
      # Some icons are not present in nerd fonts so I still need this for now.
      - otf-font-awesome
      # Hyprland itself.
      - hyprland
      # Utility to set a wallpaper.
      - hyprpaper
      # A clipboard for wayland. Mainly needed for clipse to be able to copy
      # binary data like images.
      - wl-clipboard
      # Change gtk settings like color and icon theme.
      - nwg-look
      # Allow for screen recording.
      # - xdg-desktop-portal
      - xdg-desktop-portal-hyprland
      - xdg-desktop-portal-gtk
      - xdg-desktop-portal-kde
      # App launcher.
      - fuzzel
      # A status bar for wayland compositors.
      - waybar
      # Notification deamon.
      - swaync
      # Start authentication agent for apps that need a pop up to ask for pass.
      - polkit-kde-agent
      # Applet to connect to wifi/ethernet.
      - network-manager-applet
    state: present
    # Do not installed already installed packages and assume yes to prompts.
    extra_args: --needed --noconfirm --ask=4

