- name: From repos AND AUR, install hyprland specific nececities.
  community.general.pacman:
    name:
      # Some icons are not present in nerd fonts so I still need this for now.
      - otf-font-awesome
      # Hyprland itself.
      - hyprland
      # lock utility for hyprland.
      - hyprlock
      # Utility to set a wallpaper.
      - hyprpaper
      # idle utility for hyprland.
      - hypridle
      # To make sure screensharing works.
      - pipewire
      - wireplumber
      # Needed for the hypridle config.
      - brightnessctl 
      # A clipboard for wayland. Mainly needed for clipse to be able to copy
      # binary data like images.
      - wl-clipboard
      # Needed for screenshoot script.
      - grim
      - slurp
      - hyprpicker
      # Needed to send notifications. Provides notify-send command.
      - libnotify
      # GTK3 settings editor that works on wlroots environment.
      # Not necessarily for hyprland only but wayland with wlroots is required.
      # Used to manage icons, cursor, and other settings for gtk3 apps.
      # The Gradience flatpak is used to manage color themes.
      # When installed it also goes by gtk settings.
      - nwg-look
      # adw-gtk3 is needed by the Gradience flatpak app to change gtk3 app colors.
      # adwaita colors are directly managed by Gradience without any other dependencies.
      - adw-gtk3
      # Needed to change qt apps theme.
      - qt5ct
      - qt6ct
      - qt5-wayland
      - qt6-wayland
      - kvantum
      # I like to use Catppuccin-Mocha-Yellow for QT and Ayu Dark for GTK.
      - kvantum-theme-catppuccin-git
      # Allow for screen recording.
      - xdg-desktop-portal-hyprland
      - xdg-desktop-portal-gtk
      # App launcher.
      - fuzzel
      # A status bar for wayland compositors.
      - waybar
      # Notification deamon.
      - swaync
      # Start authentication agent for apps that need a pop up to ask for pass.
      # - polkit-kde-agent
      # The kde polkit was crashing when using kvantum so this is working better.
      - mate-polkit
      # Applet to connect to wifi/ethernet.
      - network-manager-applet
      # pipewire gui for volume control of input/output devices and streams.
      - pavucontrol
      #
      # OTHER APPS that ONLY work on hyprland/wl-roots compositors.
      #
      # Record wiht hardware encoding support.
      - wl-screenrec
      # Eaach vendor, nvidia, intel, etc, provide a way to use video harware
      # acceleration. But a lot of software doesn't use that specific way.
      # Instead they use the more generic form that works on all devices, vaapi.
      # So, we need the driver for the device to use it's native video hardware
      # acceleration, such as nvidia/intel drivers. Nvidia offers NVDEC as way
      # to decode/encode video in NEWER nvidia cards.
      # But we need a layer to translate between the vaapi calls that mpv or 
      # wl-screenrec make to NVDEC.
      # For NEWER nvidia cards this is libva-nvidia-driver, then we have access
      # to vappi running on newer nvidia cards.
      # Intel is easier since the driver is pre-installed on most linux distros,
      # but we still need to the vaapi implementation.
      # The intel-media-driver works with newer intel cpus and thats all we need
      # to have acces to vaapi.
      # WARNING: only use one implementation of vaapi, I am not completely sure,
      # but I think they overlap in some way. I want to tray to use an env
      # variable to see if I can tell it which implementation to use.
      # Provides vainfo
      - libva-utils
      # Needed for vaapi to work on newer intel igpus.
      # - intel-media-driver
      # Needed for vaapi to work on newer nvidia gpus.
      # - libva-nvidia-driver
    state: present
    # Do not installed already installed packages and assume yes to prompts.
    extra_args: --needed --noconfirm --ask=4


# - name: Install packages from AUR using a Pacman compatible AUR helper
#   community.general.pacman:
#     name: foo
#     state: present
#     executable: yay
#     extra_args: --builddir /var/cache/ya
