- name: From repos AND AUR, install GUI apps and their dependencies using pacman.
  community.general.pacman:
    name:
      - visual-studio-code-bin
      # - chromium
      # MS Office alternative and spell check tools.
      - libreoffice-fresh
      - hunspell
      - hunspell-en_us
      - hunspell-es_any
      - hunspell-es_gt
      - hunspell-es_mx
      # Re-arrange pdf pages or remove them or combine multiple pdfs.
      - pdfarranger
      # GPU accelerated terminal emulator.
      #- alacritty
      #- kitty
      - wezterm
      # Disk management, partition resizer, etc.
      - gparted
      # Needed by gparted to check for errors.
      - gpart
      # Simple media player.
      - mpv
      # Add preview to mpv timeline while moving mouse over it.
      # https://github.com/po5/thumbfast
      # Better mpv gui. Make sure to remove binaries that add the ability to
      # download subtitles from the internet.
      # https://github.com/tomasklaen/uosc
      # Media player.
      - vlc
      # Image viewer. Flatpak preferred.
      # - nomacs
      # Auto detect text on PDFs/images and tools needed.
      - gimagereader-qt
      - tesseract-data-eng
      - tesseract-data-spa
      # Change mkv video metadata.
      - mkvtoolnix-gui
      # Identify and add metadata to songs.
      - picard
      # Music player.
      - strawberry
      # Torrent client.
      - qbittorrent
      # Easily add/configure printers.
      - system-config-printer
      - mediaelch
      # Install flatpaks on the system.
      - flatpak
      # Sync files between computers. Not necessarily a gui ap.
      # systemctl --user enable syncthing.service
      # systemctl --user start syncthing.service
      - syncthing
      # Disk benchmarking utility.
      - kdiskmark
      # Pixel art map/level editor. Alternative to Tiled.
      # - ldtk
      # Retroarch and needed packages. Must change config to download cores/assets from within retroarch.
      - retroarch
      # Playstation like theme.
      - retroarch-assets-xmb
      # List of cores available for download from within retroarch.
      - libretro-core-info
      # Lightroom alternative. Needs opencl for hardware
      # acceleration.
      # For nvidia cards we need opencl-nvidia
      # For intel integrated graphics we need intel-compute-runtime
      # Run darktable-cltest to check if it's working.
      # Don't forget to disable xml creation.
      - darktable
      # Photoshop alternative.
      # - gimp
      # Easier to use stable diffusion with it.
      - krita
      # Content aware healing from AUR.
      # - gimp-plugin-resynthesizer-git
      # Very complex audio editor.
      #- ardour
      # Audio editor/recorder.
      # - audacity
      # Downloads manager written in java.
      #- jdownloader2
      # - sunshine
      # - moonlight
      # - joplin
    state: present
    # Do not installed already installed packages and assume yes to prompts.
    extra_args: --needed --noconfirm --ask=4

- name: From repos AND AUR, install GNOME GUI apps and their dependencies using pacman.
  community.general.pacman:
    name:
      # Tool to change some things on gnome. Font size especially.
      - gnome-tweaks
    state: present
    # Do not installed already installed packages and assume yes to prompts.
    extra_args: --needed --noconfirm --ask=4
    when: current_DE is search("gnome")
- name: From repos AND AUR, install KDE/PLASMA GUI apps and their dependencies using pacman.
  community.general.pacman:
    name:
      # Desktop integration portals for sandboxed apps such as flatpaks, appimages and gtk apps on kde DE.
      - xdg-desktop-portal
      - xdg-desktop-portal-kde
      # Plugins for additional image formats: TIFF, MNG, TGA, WBMP
      - qt5-imageformats
      # Allow KDE pps to show thumbnails for PostScript, RAW, Mobipocket, and Blender files.
      - kdegraphics-thumbnailers
      # Needed to use nightlight plugin on kde desktop.
      - kdeplasma-addons
      # FFmpeg-based thumbnail creator for video files.
      - ffmpegthumbs
    state: present
    # Do not installed already installed packages and assume yes to prompts.
    extra_args: --needed --noconfirm --ask=4
    when: current_DE is search("plasma")

# TODO: Get file system name.
- name: From repos AND AUR, install timeshift and dependencies using pacman if using btrfs file system.
  community.general.pacman:
    name:
      # Show btrfs snapshots in the grub startup menu.
      - grub-btrfs
      # Take system snapshots. Works specially great with btrfs file system.
      - timeshift
      # Takes snapshop of system before updates automatically using timeshift.
      - timeshift-autosnap
    state: present
    # Do not installed already installed packages and assume yes to prompts.
    extra_args: --needed --noconfirm --ask=4
    when: ansible_mounts is search("btrfs")

- name: Remove conflicting packages.
  community.general.pacman:
    name:
      - libreoffice-still
    state: absent

- name: Remove conflicting plasma/kde packages.
  community.general.pacman:
    name:
      - ffmpegthumbnailer
    state: absent
    when: current_DE is search("plasma")
