# - name: NEEDS SUDO. Command to cd and make for git helper.
#   shell: "timeshift --create --comments 'Made before Ansible made changes.'"
#   when: ansible_mounts is search("btrfs")

- name: Stop and disable ssh-agent for the user.
  ansible.builtin.systemd_service:
    name: ssh-agent.service
    state: stopped
    enabled: false
    masked: false
    scope: "user"

# - name: Start and enable ssh-agent for the user.
#   ansible.builtin.systemd_service:
#     name: ssh-agent.service
#     state: started
#     enabled: true
#     masked: false
#     scope: "user"

- name: Start and enable gcr-ssh-agent.socket for the user.
  ansible.builtin.systemd_service:
    name: gcr-ssh-agent.socket
    state: started
    enabled: true
    masked: false
    scope: "user"

- name: Start and enable gcr-ssh-agent.service for the user.
  ansible.builtin.systemd_service:
    name: gcr-ssh-agent.service
    state: started
    enabled: true
    masked: false
    scope: "user"
