#!/usr/bin/env -S ansible-playbook -K

# This ansible playbook can be run locally using:
# ./local.yml
# as an executable and make the changes immediately.
# OR
# ansible-playbook local.yml -K
# OR we can use this command to run it without making any changes.
# ansible-playbook local.yml -K --diff --check
# Most tasks need root privileges and for those we specify become_user: root.
# For others we need to be the non-root user and for that we have the variable
# non_root_user: brayan.

- name: Setting Up PC
  vars:
    non_root_user: brayan
  hosts: localhost
  connection: local
  become: true
  become_method: sudo
  become_user: '{{non_root_user}}'

  tasks:
    # - name: Download binary releases from repos not found on arch.
    #   import_tasks: download_bins.yml
    #   become: true
    #   become_user: '{{non_root_user}}'

    # - name: Download binary of wallust from codeberg.
    #   import_tasks: download_wallust.yml
    #   become: true
    #   become_user: '{{non_root_user}}'

    - name: Download binary releases from repos not found on arch.
      import_tasks: download_slides.yml
      become: true
      become_user: '{{non_root_user}}'
